### ISSUE TITLE
Unable to see Camera V 1.1.143

### ISSUE THREAD

**Issue by orangevan** [andycb/AdventurerClientJS#28]
On the status page (both windows 10 app and windows native exe) i see the Camera Line, but no link for "view feed"  I know the camera works because i can navigate to http://IP:8080/?action=stream and get the feed just fine.  
Printer firmware is v1.2.1
Note, i haven't used an earlier version of this app, so i dont know if this is a regression or not.
I've seen this every time i've used the app (when i've submitted a gcode file through the app, as well as just connecting to the printer after i've submitted it via flashprint (and then disconnected from flash print so i could open this app)
![image](https://user-images.githubusercontent.com/2916616/104631105-015ecc00-5659-11eb-8c32-d0ecbdd25a9f.png)

**Comment by andycb** [comment]
Thanks for providing a detailed report. Looks like the app is getting stuck figuring out if the printer has a camera or not. 

I’m looking into reproducing it here. In the meantime the printer looks for a camera by making a request to http://<ip>:8080, would you mind confirming that on your printer this gives a webpage.

Thanks

**Comment by orangevan** [comment]
Hi Andy, thanks for the quick reply.   I can confirm my printer does not respond on that port 8080 unless i add ?action=stream  (makes me wonder if there are other URLs it does respond to)    I don't get a 404, 403 or anything, it just sits there waiting for a reply and eventually times out.  (Perhaps this changed on this firmware version?)  I just got the printer at Christmas and first thing I did was update it so I can't say if it ever did respond before.

**Comment by andycb** [comment]
Ah, that's good to know, can you try it with '/?action=snapshot' to get a still image because the app can easily check that.

**Comment by orangevan** [comment]
just tried (and a few other variations like =image, =still, =jpeg, =capture with no luck.  same thing where it just spins until a timeout.  I have tried various guess on this before because i was trying to find how to get stills but couldn't figure it out.   unfortunately the traffic to/from polarcloud is encrypted so I haven't been able to sniff it on wireshark either as they do grab stills from the device (delayed significantly though so maybe they are grabbing a short video burst i dont know and decoding?)  Anyhow no luck there.

**Comment by andycb** [comment]
Sounds like they've changed something in the firmware. According to the webpage I got on mine it supports `/?action=snapshot` and `?action=stream`. If `stream` works, I can update the app to use that and send over a pre-release build for you to test.

**Comment by orangevan** [comment]
I'd be happy to try that

**Comment by orangevan** [comment]
Hi Andy, this worked  kindof.  When i wasn't printing i could see the feed.  I sent a GX file through the app,  (that i prepared with flashprint) and when back to status and clicked View feed.  i had a second of feed, then it disconnected (while my view through firefox stayed running)  Back on status page then it said it wasn't able to connect to the feed with a link to "view help"  I disconnected and reconnected a few times and now i can see the feed again and it looks good.   Perhaps adding a refresh button next to the Camera line in case of temporary glitches like this.. (maybe your program already auto refreshes on an interval? if so, there isn't any visual indication this is happening so i did the disconnect and reconnect method on my end which may have not been necessary)

All in all, this is awesome!  Thanks for tweaking for me so quick on this.

It seems if i return the the status page, and then go back to the camera feed a few seconds later i get the very short burst of video (maybe only 5 frames) and then error.    This time i disconnected and reconnected 5 times before it came back with "view feed"      This behavior is repeatable.   I dont know if the app is having troubles with the multiple concurrent attempts to access the same steaming url (once for the check and again for the actual viewing?)
It seems that after some amount of time (60 seconds maybe?) i am able to reconnect.  

I refreshed my browser version of this URL while the app wasn't connecting and i got an immediate "connection was reset" error so i believe the streaming server is rejecting connections as it probably has a limited number that it will support concurrently.  (Wish they had that =snapshot option on this firmware/hardware revision)

So this being said, i think, if you get a successful stream connection to where you can provide the "view feed" link, perhaps you can have it automatically view the feed and have it to the right of all the status data so you can see both at the same time?  THis would be awesome (i understand that not everyone would want that so maybe a checkbox to enable/disable auto view feed)  I personally like having the feed AND the data at the same time.

Sorry for the novel

**Comment by orangevan** [comment]
Okay so update.  I've done some more testing.   
If i close the app (native windows exe) and reopen it, reconnect to printer, it seems to work (3 times in a row successful) but as soon as i leave the feed to go to status, and then come back, it get a few frames then disconnected with difficultly reconnecting.  (closing the exe and re-launching seems to fix)

Looking in resource monitor, when edge is connected to the feed or firefox, i only see one connection to the printer on port 8080 for the stream.  With Adventure Client, when i switch to status, and then try to return, it opens a new TCP connection when i still see the old one active in Resource monitor (bandwidth still chomping away)  so my deduction is that when you are leaving the feed, the existing TCP connection isn't being closed and its trying to open a new one from the same PID (different local tcp port) and for whatever reason the streaming server doesn't like that.

When i close the application the bandwidth usage immediately stops (so those TCP connections are killed) and i'm able to reconnect to the feed first try.  Hope that helps.

**Comment by andycb** [comment]
Firstly – huge thanks for taking the time to research this so thoroughly, this is really useful for getting to the bottom of this.

The app refreshes the connection on the status page every 5 seconds an M119, M115, and M115 down the connection to the printer on port 8899 to get the print stats. It then makes a web request to the printer on port 8080 to test if the camera is enabled. 

While you’re viewing the feed, this refresh is stopped and replaced by a check every 5 seconds to check if the camera is still available (because is the camera is in auto mode and the print finishes, the camera will turn off).

In theory, it’s now testing the camera by connecting to the stream, waiting for the first byte then aborting the connection. From your investigation, it seems that isn’t working as expected and its overwhelming the printer.

I’ll take a second look and see what I missed.

RE: Showing the feed on the main page – The more I think of it, the more it makes sense to show the feed alongside the other data – something I’ll give some thought to once we’ve made it work reliably for you :)

**Comment by orangevan** [comment]
From what i can tell, once i've opened the feed, it starts pulling data and if i return to status it keeps pulling the data (based on monitoring bandwidth and resource monitor and wireshark) and the stream is still coming in.  THen trying to open another and it dies.  Note i have had the printer running a couple simultaneous streams no problem (browser and VLC on phone at the same time)
I'm happy to try any tweaks out as you have time to make them.  Thanks again!

**Comment by andycb** [comment]
Okay, this was adventure. 

On the older printer firmware versions, the camera server was powered by an open source project that doesn’t seem to have received much love in a while. My guess is that the newer firmware versions have moved to something else, which is why only the stream link works now. In both cases, it seems to be streaming an MJPEG which has pretty patchy support in the browsers.

You’re right about the view feed page leaving connections open, so I think there’s a couple of things going on here: 
1 - The feed page is checking the camera stream every second to see if it is enabled, which may be stressing the printer server a little.
2 – The open connections are probably acuminating and we’re hitting a TCP connection limit in Chromium.

 I’ve made a few changes to be gentler on the printer in the hope that helps:
-	The connection is now properly closed when leaving the feed page (in resource monitor you should see one black connection to the printer open the whole time and one intermittent connection to port 8080 for the check. It will show some old greyed out ones for a while, but these are okay as they’re released)
-	The camera enabled check is slowed down to ever 5 seconds (I tried to use events off the img element to check the status of the actual stream, rather than using a second connection. But I hit an issue where Chromium does not raise events in the same way as Firefox for MJPEG streams, so wasn’t able to)
-	The app will now wait longer before giving up on a connection.

An updated build is here if you want to give it a go: https://github.com/andycb/AdventurerClientJS/releases/tag/v1.2.108-bu

**Comment by orangevan** [comment]
Hey Andy,
So i've tested this again (confirming build 1.2.108, 64 bit windows exe not store app) and when leaving the feed page, the bandwidth doesn't drop, nor does the connection switch in resource monitor to grey.  I clicked view feed a second time, and the bandwidth usage doubled and then stopped showing video (but connections remained) 
If i disconnect from the printer it doesn't help. 
![image](https://user-images.githubusercontent.com/2916616/104957576-a47e5100-598b-11eb-8201-6916819c43f0.png)

**Comment by andycb** [comment]
With some joy I just managed to reproduce this - seems like it might be intermittent, I had to keep going forwards and backwards a few times.... I'll continue investigating

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4417762/104966454-d073f380-59d8-11eb-83b0-fa5da88f81f4.png">

**Comment by orangevan** [comment]
Well now that is working super slick!  (1.2.109)  Video comes up right away and closes properly. I haven't been able to mess it up.
Thanks Andy!!  (Now to just have this and the status data on the same screen at the same time.  Do you want me to put in a issue for you to track this as an enhancement?)

**Comment by andycb** [comment]
Fantastic! Got there in the end. That’s for your patience testing it. I’ll fix a couple of the ither issues before I push out though the store. I generally like to call out contributors (code, time, suggestions), would you be okay being called out in the release notes / about page?

Yes, please open an issue for that enhancement.

**Comment by orangevan** [comment]
I don't mind, but also not necessary!  Thanks for fixing it, super pumped!
